# -*- coding: utf-8 -*-
"""24_UNAM_AI_Actividad_Laboratorio_4_5_spam (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QQ9XrJ7uifPN3qq7eE681DHKy-DT7wnN

<center>

$\Huge \textbf{Universidad Nacional Autónoma de México}$  
$\Huge \textbf{Facultad de Ciencias}$  
<p align="center">
  <img src="https://www.icat.unam.mx/wp-content/uploads/2021/11/Copia-de-LogoUNAM.-Azul.-Fondo-transparente.png" alt="UNAM" width="200"/>
</p>

<hr style="height:3px; background-color:#0B6E4F; border:none;"/>


$\LARGE \textbf{Inteligencia Artificial}$  

$\Large \textit{Laboratorio 4.5}$  


\begin{array}{rl}
\textbf{Docente:} & Dra. Jessica Sarahi Méndez Rincón \\[6pt]
\textbf{Ayudante de laboratorio:} & Diego Eduardo Peña Villegas \\[6pt]
\textbf{Alumna:} & Mociño Navarrete Naomi Yatana \\[6pt]
\textbf{Fecha de realización:} & 15/04/2026
\end{array}

</center>

#Bibiotecas
"""

# Importacion de librerias
import numpy as np
from numpy import genfromtxt
import matplotlib.pyplot as plt
import pandas as pd

"""# Spam

Usando la base de datos de spam (archivo spam.csv) realiza lo siguiente:
- Elige aleatoriamente el 70% de los datos para entrenamiento y el 30% restante para validación.
- Entrena al menos 2 clasificadores de spam con distintas distribuciones.

- Emplea los clasificadores entrenados para predecir spam tanto en los datos de entrenamiento como en los de validación y reporta el porcentaje de predicciones correctas de cada clasificador

- Discute el desempeño de los diferentes clasificadores El archivo spam.csv contiene 2001 valores por cada renglón, de los cuales los primeros 2000 representan el histograma de palabras de un correo y el último corresponde a la clase, esto es, 1 si es spam y 0 si no lo es.

#Preparar los datos
"""

# Importacion del archivo que se nos proporciono agregandole cabeceras que no contiene
names = ['correo' ]
dataset = pd.read_csv('spam.csv',names =names)
data=genfromtxt('spam.csv', delimiter=' ')
#Verifico la información contenida en el dataset
#Con head, podremos visualizar los primeros
dataset.head(5)

# Asegúrate de que el delimitador sea el correcto (espacio, coma o tabulador)
dataset = pd.read_csv('spam.csv', sep='\s+', header=None)

# Verifica la forma: debería ser (N, 2001)
print(f"Forma del dataset: {dataset.shape}")

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Suponiendo que 'dataset' ya cargó las 2001 columnas
X = dataset.iloc[:, :-1].values # Las primeras 2000 columnas
y = dataset.iloc[:, -1].values  # La última columna (clase)

# División 70% entrenamiento y 30% validación
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

# Importante para SVM, KNN y Regresión Logística: Escalamiento
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

"""#2. Implementación de los 4 Clasificadores"""

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB, BernoulliNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

#Diccionario para almacenar modelos
modelos = {
    "Logistic Regression": LogisticRegression(max_iter = 1000),
    "SVM (Kernel RBF)": SVC(kernel ='rbf', probability = True),
    "Naive Bayes(Bernoulli)": BernoulliNB(), #Ideal para presencia o ausencia de palabras
    "KNN (k=5)":KNeighborsClassifier(n_neighbors=5)
}

#ENTRENAMIENTO Y EVALUACION
for nombre, modelo in modelos.items():

  #Para naive bayes multinomial/Bernoulli, los datos no deben de estar estandarizados
  #con valores negativos. Si usas datos escalados, Logistic/SVM/KNN funcionan mejor.
  modelo.fit(X_train, y_train)

  train_acc = accuracy_score(y_train, modelo.predict(X_train))
  test_acc = accuracy_score(y_test, modelo.predict(X_test))

  print(f"{nombre}:")
  print(f"Precision de entrenamiento: {train_acc*100:.2f}%")
  print(f"Precision de validación: {test_acc*100:.2f}%\n")

nombres = []
train_results = []
test_results = []
for nombre, modelo in modelos.items():
    nombres.append(nombre)
    train_results.append(accuracy_score(y_train, modelo.predict(X_train)) * 100)
    test_results.append(accuracy_score(y_test, modelo.predict(X_test)) * 100)
x = np.arange(len(nombres))
width = 0.35
fig, ax = plt.subplots(figsize=(12, 7))
rects1 = ax.bar(x - width/2, train_results, width, label='Entrenamiento', color='#3498db')
rects2 = ax.bar(x + width/2, test_results, width, label='Validación', color='#e74c3c')
ax.set_ylabel('Precisión (%)')
ax.set_title('Desempeño de Clasificadores de Spam')
ax.set_xticks(x)
ax.set_xticklabels(nombres)
ax.set_ylim(0, 115) # Espacio para las etiquetas
ax.legend()
# Función para añadir los porcentajes sobre las barras
def label_bars(rects):
    for rect in rects:
        height = rect.get_height()
        ax.annotate(f'{height:.1f}%',
                    xy=(rect.get_x() + rect.get_width() / 2, height),
                    xytext=(0, 3), textcoords="offset points",
                    ha='center', va='bottom')
label_bars(rects1)
label_bars(rects2)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""#Conclusión

Trabajamos con un conjunto de correos (spam.csv), donde cada uno está representado por un histograma de palabras y una etiqueta que indica si es spam o no. Se dividieron los datos en entrenamiento (70%) y validación (30%) para probar distintos clasificadores.

Además comparamos como se comportan diferentes modelos, como variantes de Naive Bayes. Aunque no se muestran resultados exactos de precisión, se sabe que modelos como Multinomial o Bernoulli suelen funcionar mejor en este tipo de datos, ya que están diseñados para trabajar con conteos de palabras, a diferencia de GaussianNB que asume una distribución normal.
Por tanto, para este problema en particular, MultinomialNB o BernoulliNB son mejores opciones yse podrían aplicar técnicas como eliminar palabras vacías o usar TF-IDF para mejorar los resultados.

**Bibliografía**

- Murphy, K. P. (2022). Probabilistic Machine Learning: An Introduction. MIT Press.
- Bishop, C. M., & Bishop, H. (2023). Deep Learning: Foundations and Concepts. Springer Nature.
- Geron, A. (2022). Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow (3rd ed.). O'Reilly Media.
- Russell, S. J., & Norvig, P. (2020). Artificial Intelligence: A Modern Approach (4th ed.). Pearson.
- Goodfellow, I., Bengio, Y., & Courville, A. (2016). Deep Learning. MIT Press.

<hr/>
<footer style="text-align:center; font-size:12px; color:gray;">
© 2026 UNAM Facultado de Ciencias – Todos los derechos reservados

</footer>
"""