# -*- coding: utf-8 -*-
"""22_UNAM_AI_Actividad_Laboratorio_4_3_radio (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rsvERof-lA02UlIbXdY5XQUP1uJ_-y_R

<center>

$\Huge \textbf{Universidad Nacional Autónoma de México}$  
$\Huge \textbf{Facultad de Ciencias}$  
<p align="center">
  <img src="https://www.icat.unam.mx/wp-content/uploads/2021/11/Copia-de-LogoUNAM.-Azul.-Fondo-transparente.png" alt="UNAM" width="200"/>
</p>

<hr style="height:3px; background-color:#0B6E4F; border:none;"/>


$\LARGE \textbf{Inteligencia Artificial}$  

$\Large \textit{Laboratorio 2.3}$  


\begin{array}{rl}
\textbf{Docente:} & Dra. Jessica Sarahi Méndez Rincón \\[6pt]
\textbf{Ayudante de laboratorio:} & Diego Eduardo Peña Villegas \\[6pt]
\textbf{Alumna:} & Mociño Navarrete Naomi Yatana \\[6pt]
\textbf{Fecha de realización:} & 15/04/2026
\end{array}

</center>

Programar un clasificador Naive Bayes desde cero es un excelente ejercicio para entender cómo funcionan las verosimilitudes y las probabilidades posteriores.

Aquí tienes la implementación en Python usando numpy para facilitar las operaciones vectoriales que calcula tanto MLE como MAP (Suavizado de Laplace) siguiendo el procedimiento matemático.

#Bibliotecas
"""

# Importacion de librerias
import numpy as np
from numpy import genfromtxt
import matplotlib.pyplot as plt
import pandas as pd

"""Una estación de radio busca clasificar a su audiencia en jóvenes y adultos a partir de sus gustos
musicales. Para esto la estación realizó una encuesta la cual consistía en indicar si les gustaba cierta
agrupación (valor igual a 1) o no (valor igual a 0) y se obtuvieron los siguientes resultados:
"""

# Importacion del archivo que se nos proporciono agregandole cabeceras que no contiene
dataset = pd.read_csv('radio.csv')
#Con head, podremos visualizar los primeros
print(dataset)

"""Entrena un clasificador bayesiano ingenuo usando estimación por máxima verosimilitud y otro
usando estimación por máximo a posteriori. Reporta los parámetros que obtuviste en ambos casos y
usa los clasificadores entrenados para predecir la clase de los siguientes vectores

x1 = (1, 1, 0, 1, 1, 0),

x2 = (1, 0, 1, 1, 1, 1),

x3 = (1, 1, 0, 0, 0, 0),

x4 = (1, 1, 1, 1, 1, 1) y

x5 = (0, 1, 1, 1, 1, 1).

Describe de forma detallada el procedimiento que seguiste tanto en el entrenamiento como en la predicción y
discute los resultados obtenidos

#ESTABLECIMIENTO DE AUDIENCIA O VECTORES
"""

X1=np.array([1,1,0,1,1,0])
X2=np.array([1,0,1,1,1,1])
X3=np.array([1,1,0,0,0,0])
X4=np.array([1,1,1,1,1,1])
X5=np.array([0,1,1,1,1,1])
print("X1=",X1)
print("X2=",X2)
print("X3=",X3)
print("X4=",X4)
print("X5=",X5)

"""#PREPARAR LOS DATOS"""

#print(dataset)
datos = dataset.iloc[0:13,0:6].values
#print(data)
clase_joven = datos[[0,1,2,3,4,5], :]
print("clase Joven=>\n", clase_joven)
clase_adulto = datos[[6,7,8,9,10,11,12], :]
print("clase Adulto=>\n", clase_adulto)
aprioriJ=6/13
aprioriA=7/13

dataset.hist()
plt.show()

lista = dataset.iloc[:,6:7].values
#print(lista)
apriori_joven = 6/13
print("Pj =",apriori_joven)
apriori_adulto = 7/13
print("Pa =",apriori_adulto)

"""#Con librerías pre-establecidas"""

import numpy as np
import pandas as pd
from sklearn.naive_bayes import CategoricalNB

# 1. Creamos el dataset basado en la matriz
data = {
    'w1': [1,1,1,1,1,1, 1,1,1,1,1,1,1],
    'w2': [0,1,1,0,0,1, 1,1,1,1,1,1,1],
    'w3': [0,0,1,1,0,1, 0,1,1,1,1,0,0],
    'w4': [1,1,0,0,0,0, 0,0,1,0,0,1,1],
    'w5': [1,1,0,0,1,0, 1,0,1,1,1,1,0],
    'w6': [1,0,1,1,0,0, 1,1,0,0,1,0,0],
    'E':  ['j','j','j','j','j','j', 'a','a','a','a','a','a','a']
}

df = pd.DataFrame(data)
X = df.drop('E', axis=1)
y = df['E']

# Vectores a predecir
X_test = np.array([
    [1, 1, 0, 1, 1, 0], # x1
    [1, 0, 1, 1, 1, 1], # x2
    [1, 1, 0, 0, 0, 0], # x3
    [1, 1, 1, 1, 1, 1], # x4
    [0, 1, 1, 1, 1, 1]  # x5
])

# ---------------------------------------------------------
# 2. Estimación por Máxima Verosimilitud (MLE)
# Usamos un alpha insignificante para simular MLE puro
mle_model = CategoricalNB(alpha=1e-10)
mle_model.fit(X, y)

# ---------------------------------------------------------
# 3. Estimación por Máximo a Posteriori (MAP)
# alpha=1 aplica el Suavizado de Laplace
map_model = CategoricalNB(alpha=1.0)
map_model.fit(X, y)

# ---------------------------------------------------------
# 4. Reporte de resultados
def reportar(modelo, nombre):
    preds = modelo.predict(X_test)
    probs = modelo.predict_proba(X_test)
    print(f"\n--- Resultados con {nombre} ---")
    for i, p in enumerate(preds):
        prob_j = probs[i][1] # j suele ser el segundo índice alfabéticamente
        prob_a = probs[i][0]
        print(f"x{i+1}: Predicción -> {p} | P(a)={prob_a:.3f}, P(j)={prob_j:.3f}")

reportar(mle_model, "MLE (Máxima Verosimilitud)")
reportar(map_model, "MAP (Suavizado de Laplace)")

"""#Detalles del procedimiento:

- Codificación: CategoricalNB es el modelo ideal aquí porque tus variables son categóricas (gustos musicales 0 o 1) y no siguen una distribución normal (como lo asumiría un GaussianNB).
- Entrenamiento (.fit): Durante este paso, el modelo calcula internamente las tablas de frecuencias que definimos manualmente arriba. Calcula cuántas veces aparece cada gusto por cada clase.
- Predicción (.predict): El modelo aplica el Teorema de Bayes. Multiplica la probabilidad previa de la clase por todas las probabilidades condicionales de los atributos presentes en los vectores $x_1 \dots x_5$.
- Manejo de Ceros: Si intentas predecir $x_5$ con MLE, notarás algo interesante: $x_5$ tiene $w_1 = 0$. En tus datos de entrenamiento, $w_1$ siempre es 1. Un modelo MLE puro daría una probabilidad de 0% para ambas clases (un error matemático), mientras que el modelo MAP (Laplace) le asignará una probabilidad pequeña pero real, permitiendo la clasificación.

#ESTABLECIMIENTO DE FUNCIONES DE AYUDA
"""

import numpy as np
import pandas as pd

# 1. Datos de la imagen
data = {
    'w1': [1,1,1,1,1,1, 1,1,1,1,1,1,1],
    'w2': [0,1,1,0,0,1, 1,1,1,1,1,1,1],
    'w3': [0,0,1,1,0,1, 0,1,1,1,1,0,0],
    'w4': [1,1,0,0,0,0, 0,0,1,0,0,1,1],
    'w5': [1,1,0,0,1,0, 1,0,1,1,1,1,0],
    'w6': [1,0,1,1,0,0, 1,1,0,0,1,0,0],
    'E':  ['j','j','j','j','j','j', 'a','a','a','a','a','a','a']
}

df = pd.DataFrame(data)
clases = df['E'].unique() # ['j', 'a']

# Vectores a predecir
X_test = [
    [1, 1, 0, 1, 1, 0], # x1
    [1, 0, 1, 1, 1, 1], # x2
    [1, 1, 0, 0, 0, 0], # x3
    [1, 1, 1, 1, 1, 1], # x4
    [0, 1, 1, 1, 1, 1]  # x5
]

def entrenar_naive_bayes(df, suavizado=0):
    """
    Entrena el modelo calculando priors y verosimilitudes.
    suavizado=0 para MLE, suavizado=1 para MAP (Laplace).
    """
    modelo = {}
    N = len(df)

    for c in clases:
        df_c = df[df['E'] == c]
        n_c = len(df_c)

        # P(C) - Prior
        prior = n_c / N

        # P(wi=1 | C) - Verosimilitudes para cada atributo
        # Aplicamos la fórmula: (conteo + alpha) / (total + alpha * k)
        # k=2 porque las categorías son binarias (0 o 1)
        probs_condicionales = {}
        for col in ['w1', 'w2', 'w3', 'w4', 'w5', 'w6']:
            conteo_1 = df_c[col].sum()
            prob = (conteo_1 + suavizado) / (n_c + suavizado * 2)
            probs_condicionales[col] = prob

        modelo[c] = {'prior': prior, 'condicionales': probs_condicionales}

    return modelo

def predecir(vector, modelo):
    resultados = {}

    for c, params in modelo.items():
        # Comenzamos con el Prior: P(C)
        prob_final = params['prior']

        # Multiplicamos por cada P(wi | C)
        for i, valor in enumerate(vector):
            col = f'w{i+1}'
            p_exito = params['condicionales'][col]

            # Si el vector tiene 1, usamos p_exito. Si tiene 0, usamos (1 - p_exito)
            if valor == 1:
                prob_final *= p_exito
            else:
                prob_final *= (1 - p_exito)

        resultados[c] = prob_final

    # Normalizar para que sumen 1 (opcional, para ver porcentajes)
    total = sum(resultados.values())
    if total > 0:
        for c in resultados: resultados[c] /= total

    return max(resultados, key=resultados.get), resultados

# --- Ejecución ---

# Entrenar ambos modelos
modelo_mle = entrenar_naive_bayes(df, suavizado=0)
modelo_map = entrenar_naive_bayes(df, suavizado=1)

print("PREDICCIONES DESDE CERO")
for i, x in enumerate(X_test):
    clase_mle, _ = predecir(x, modelo_mle)
    clase_map, probs_map = predecir(x, modelo_map)

    print(f"\nx{i+1} {x}:")
    print(f"  MLE -> {clase_mle}")
    print(f"  MAP -> {clase_map} (P(j): {probs_map['j']:.4f}, P(a): {probs_map['a']:.4f})")

"""Explicación de la Lógica entrenar_naive_bayes:

- Priors: Es simplemente la proporción de cada clase en el total de la muestra.- Verosimilitudes: Para cada columna $w_i$, contamos cuántos "1" hay. En MLE, dividimos entre el total de la clase.

En MAP, sumamos 1 al numerador y 2 al denominador (Suavizado de Laplace) para evitar que una probabilidad sea exactamente 0.

predecir:

- Implementa la productoria $\prod P(w_i | C)$.
- Punto clave: Si el vector de entrada tiene un $0$ en una posición, debemos usar el complemento de la probabilidad calculada ($1 - P(w_i=1|C)$).

Observación sobre el vector $x_5$Si observas el vector $x_5 = (0, 1, 1, 1, 1, 1)$, notarás que empieza con un 0. Sin embargo, en tu dataset de entrenamiento, $w_1$ siempre es 1 para ambas clases.
- En MLE, $P(w_1=0 | C)$ será $0$, por lo que la probabilidad final de ambas clases será $0$. El modelo "se rompe" porque nunca ha visto un cero ahí.
- En MAP, gracias al $+1$ del suavizado, $P(w_1=0 | C)$ tendrá un valor pequeño pero mayor a cero, permitiendo que el resto de los atributos decidan la clase.

#Conclusión

Al parecer los datos con el Bayesiano Ingenio Suave, realiza incluso una verificación más precisa ya que toma cada uno de los valores anteriores de cada clase. La diferencia Radica principalmente en que en un vector no se complementan, como lo abordo en el ejercicio a lápiz, en el momento en que se obtiene el complemento ambas clases contienen información por lo tanto el complemento es nulo y eso afecta a toda la multiplicación de probabilidad y hace que el elemento sea marcado como indefinido. De esta manera se ve que es más preciso el segundo estimador, por que contemplo la suma.

Conclusiones

El estimador MAP es más confiable que MLE porque evita probabilidades cero ante valores no vistos en entrenamiento. Esto se evidencia en el vector `x5`, donde `w1=0` no aparece en los datos de entrenamiento: MLE no puede clasificarlo (probabilidad cero), mientras que MAP asigna una probabilidad pequeña pero válida y logra predecir la clase "adulto". Por esta razón, MAP es preferible sobre MLE en problemas con datos limitados o características poco representadas.

# Bibliografía

- Murphy, K. P. (2022). Probabilistic Machine Learning: An Introduction. MIT Press.
- Bishop, C. M., & Bishop, H. (2023). Deep Learning: Foundations and Concepts. Springer Nature.
- Geron, A. (2022). Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow (3rd ed.). O'Reilly Media.
- Russell, S. J., & Norvig, P. (2020). Artificial Intelligence: A Modern Approach (4th ed.). Pearson.
- Goodfellow, I., Bengio, Y., & Courville, A. (2016). Deep Learning. MIT Press.

<hr/>
<footer style="text-align:center; font-size:12px; color:gray;">
© 2026 UNAM Facultado de Ciencias – Todos los derechos reservados

</footer>
"""